// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/base.proto

package com.xxicon.poker.message;

public final class Base {
  private Base() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_Header_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_C0001_HeartbeatReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_C0001_HeartbeatReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_C0001_HeartbeatResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_C0001_HeartbeatResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_C0002_ToastResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_C0002_ToastResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_C0003_ToastResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_C0003_ToastResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020proto/base.proto\022\010messages\"\"\n\006Header\022\n" +
      "\n\002id\030\001 \001(\021\022\014\n\004data\030\002 \001(\014\"\024\n\022C0001_Heartb" +
      "eatReq\"\025\n\023C0001_HeartbeatResp\"\"\n\017C0002_T" +
      "oastResp\022\017\n\007message\030\001 \001(\t\"0\n\017C0003_Toast" +
      "Resp\022\017\n\007message\030\001 \001(\t\022\014\n\004type\030\002 \001(\005B\034\n\030c" +
      "om.xxicon.poker.messageP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_messages_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_Header_descriptor,
        new java.lang.String[] { "Id", "Data", });
    internal_static_messages_C0001_HeartbeatReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_messages_C0001_HeartbeatReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_C0001_HeartbeatReq_descriptor,
        new java.lang.String[] { });
    internal_static_messages_C0001_HeartbeatResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_messages_C0001_HeartbeatResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_C0001_HeartbeatResp_descriptor,
        new java.lang.String[] { });
    internal_static_messages_C0002_ToastResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_messages_C0002_ToastResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_C0002_ToastResp_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_messages_C0003_ToastResp_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_messages_C0003_ToastResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_C0003_ToastResp_descriptor,
        new java.lang.String[] { "Message", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
