// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/base.proto

package com.xxicon.poker.message;

public interface C0001_HeartbeatReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0001_HeartbeatReq)
    com.google.protobuf.MessageOrBuilder {
}
