// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/role.proto

package com.xxicon.poker.message;

public interface C0106_RoleLoginRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0106_RoleLoginResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>.messages.RoleInfo info = 3;</code>
   * @return Whether the info field is set.
   */
  boolean hasInfo();
  /**
   * <code>.messages.RoleInfo info = 3;</code>
   * @return The info.
   */
  com.xxicon.poker.message.RoleInfo getInfo();
  /**
   * <code>.messages.RoleInfo info = 3;</code>
   */
  com.xxicon.poker.message.RoleInfoOrBuilder getInfoOrBuilder();
}
