// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/role.proto

package com.xxicon.poker.message;

public interface C0105_RoleRegisterReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0105_RoleRegisterReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 角色名
   * </pre>
   *
   * <code>string roleName = 1;</code>
   * @return The roleName.
   */
  java.lang.String getRoleName();
  /**
   * <pre>
   * 角色名
   * </pre>
   *
   * <code>string roleName = 1;</code>
   * @return The bytes for roleName.
   */
  com.google.protobuf.ByteString
      getRoleNameBytes();

  /**
   * <pre>
   * 性别 0=女, 1=男
   * </pre>
   *
   * <code>int32 gender = 2;</code>
   * @return The gender.
   */
  int getGender();
}
