// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/role.proto

package com.xxicon.poker.message;

public interface C0106_RoleLoginReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0106_RoleLoginReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 roleId = 1;</code>
   * @return The roleId.
   */
  int getRoleId();
}
