// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/role.proto

package com.xxicon.poker.message;

public interface C0102_ReconnectReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0102_ReconnectReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session = 1;</code>
   * @return The session.
   */
  java.lang.String getSession();
  /**
   * <code>string session = 1;</code>
   * @return The bytes for session.
   */
  com.google.protobuf.ByteString
      getSessionBytes();
}
