// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/role.proto

package com.xxicon.poker.message;

public interface C0120_RoleAttributeRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0120_RoleAttributeResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 等级
   * </pre>
   *
   * <code>int32 level = 1;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <pre>
   * 金钱数
   * </pre>
   *
   * <code>int32 money = 2;</code>
   * @return The money.
   */
  int getMoney();
}
