// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/chat.proto

package com.xxicon.poker.message;

public interface C0200_ChatNewsRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0200_ChatNewsResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *频道 0=系统, 1=私聊, 2=房间, 3=世界
   * </pre>
   *
   * <code>int32 channel = 1;</code>
   * @return The channel.
   */
  int getChannel();

  /**
   * <code>.messages.ChatInfo info = 2;</code>
   * @return Whether the info field is set.
   */
  boolean hasInfo();
  /**
   * <code>.messages.ChatInfo info = 2;</code>
   * @return The info.
   */
  com.xxicon.poker.message.ChatInfo getInfo();
  /**
   * <code>.messages.ChatInfo info = 2;</code>
   */
  com.xxicon.poker.message.ChatInfoOrBuilder getInfoOrBuilder();
}
