// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/chat.proto

package com.xxicon.poker.message;

public interface C0201_ChatSendReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0201_ChatSendReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *频道
   * </pre>
   *
   * <code>int32 channel = 1;</code>
   * @return The channel.
   */
  int getChannel();

  /**
   * <pre>
   * 内容
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 内容
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 目标： 私聊频道为角色ID，房间频道为房间号
   * </pre>
   *
   * <code>string target = 3;</code>
   * @return The target.
   */
  java.lang.String getTarget();
  /**
   * <pre>
   * 目标： 私聊频道为角色ID，房间频道为房间号
   * </pre>
   *
   * <code>string target = 3;</code>
   * @return The bytes for target.
   */
  com.google.protobuf.ByteString
      getTargetBytes();
}
