// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

public interface C0302_RoomEnterReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0302_RoomEnterReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 房间号
   * </pre>
   *
   * <code>int32 roomId = 1;</code>
   * @return The roomId.
   */
  int getRoomId();

  /**
   * <pre>
   * 房间密码
   * </pre>
   *
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <pre>
   * 房间密码
   * </pre>
   *
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
