// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

public interface C0305_RoomReMatchReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0305_RoomReMatchReq)
    com.google.protobuf.MessageOrBuilder {
}
