// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

/**
 * <pre>
 * 房间状态同步
 * </pre>
 *
 * Protobuf type {@code messages.C0300_RoomSyncResp}
 */
public  final class C0300_RoomSyncResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:messages.C0300_RoomSyncResp)
    C0300_RoomSyncRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use C0300_RoomSyncResp.newBuilder() to construct.
  private C0300_RoomSyncResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private C0300_RoomSyncResp() {
    infos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new C0300_RoomSyncResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private C0300_RoomSyncResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            ownerId_ = input.readInt32();
            break;
          }
          case 16: {

            roomId_ = input.readInt32();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              infos_ = new java.util.ArrayList<com.xxicon.poker.message.RoomRoleInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            infos_.add(
                input.readMessage(com.xxicon.poker.message.RoomRoleInfo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        infos_ = java.util.Collections.unmodifiableList(infos_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xxicon.poker.message.Room.internal_static_messages_C0300_RoomSyncResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xxicon.poker.message.Room.internal_static_messages_C0300_RoomSyncResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xxicon.poker.message.C0300_RoomSyncResp.class, com.xxicon.poker.message.C0300_RoomSyncResp.Builder.class);
  }

  public static final int OWNERID_FIELD_NUMBER = 1;
  private int ownerId_;
  /**
   * <pre>
   * 房主角色ID
   * </pre>
   *
   * <code>int32 ownerId = 1;</code>
   * @return The ownerId.
   */
  public int getOwnerId() {
    return ownerId_;
  }

  public static final int ROOMID_FIELD_NUMBER = 2;
  private int roomId_;
  /**
   * <code>int32 roomId = 2;</code>
   * @return The roomId.
   */
  public int getRoomId() {
    return roomId_;
  }

  public static final int INFOS_FIELD_NUMBER = 3;
  private java.util.List<com.xxicon.poker.message.RoomRoleInfo> infos_;
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
   */
  public java.util.List<com.xxicon.poker.message.RoomRoleInfo> getInfosList() {
    return infos_;
  }
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
   */
  public java.util.List<? extends com.xxicon.poker.message.RoomRoleInfoOrBuilder> 
      getInfosOrBuilderList() {
    return infos_;
  }
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
   */
  public int getInfosCount() {
    return infos_.size();
  }
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
   */
  public com.xxicon.poker.message.RoomRoleInfo getInfos(int index) {
    return infos_.get(index);
  }
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
   */
  public com.xxicon.poker.message.RoomRoleInfoOrBuilder getInfosOrBuilder(
      int index) {
    return infos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ownerId_ != 0) {
      output.writeInt32(1, ownerId_);
    }
    if (roomId_ != 0) {
      output.writeInt32(2, roomId_);
    }
    for (int i = 0; i < infos_.size(); i++) {
      output.writeMessage(3, infos_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ownerId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ownerId_);
    }
    if (roomId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, roomId_);
    }
    for (int i = 0; i < infos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, infos_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xxicon.poker.message.C0300_RoomSyncResp)) {
      return super.equals(obj);
    }
    com.xxicon.poker.message.C0300_RoomSyncResp other = (com.xxicon.poker.message.C0300_RoomSyncResp) obj;

    if (getOwnerId()
        != other.getOwnerId()) return false;
    if (getRoomId()
        != other.getRoomId()) return false;
    if (!getInfosList()
        .equals(other.getInfosList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OWNERID_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerId();
    hash = (37 * hash) + ROOMID_FIELD_NUMBER;
    hash = (53 * hash) + getRoomId();
    if (getInfosCount() > 0) {
      hash = (37 * hash) + INFOS_FIELD_NUMBER;
      hash = (53 * hash) + getInfosList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xxicon.poker.message.C0300_RoomSyncResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxicon.poker.message.C0300_RoomSyncResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0300_RoomSyncResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxicon.poker.message.C0300_RoomSyncResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0300_RoomSyncResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxicon.poker.message.C0300_RoomSyncResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0300_RoomSyncResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xxicon.poker.message.C0300_RoomSyncResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0300_RoomSyncResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xxicon.poker.message.C0300_RoomSyncResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0300_RoomSyncResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xxicon.poker.message.C0300_RoomSyncResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xxicon.poker.message.C0300_RoomSyncResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 房间状态同步
   * </pre>
   *
   * Protobuf type {@code messages.C0300_RoomSyncResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:messages.C0300_RoomSyncResp)
      com.xxicon.poker.message.C0300_RoomSyncRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xxicon.poker.message.Room.internal_static_messages_C0300_RoomSyncResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xxicon.poker.message.Room.internal_static_messages_C0300_RoomSyncResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xxicon.poker.message.C0300_RoomSyncResp.class, com.xxicon.poker.message.C0300_RoomSyncResp.Builder.class);
    }

    // Construct using com.xxicon.poker.message.C0300_RoomSyncResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getInfosFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ownerId_ = 0;

      roomId_ = 0;

      if (infosBuilder_ == null) {
        infos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        infosBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xxicon.poker.message.Room.internal_static_messages_C0300_RoomSyncResp_descriptor;
    }

    @java.lang.Override
    public com.xxicon.poker.message.C0300_RoomSyncResp getDefaultInstanceForType() {
      return com.xxicon.poker.message.C0300_RoomSyncResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.xxicon.poker.message.C0300_RoomSyncResp build() {
      com.xxicon.poker.message.C0300_RoomSyncResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xxicon.poker.message.C0300_RoomSyncResp buildPartial() {
      com.xxicon.poker.message.C0300_RoomSyncResp result = new com.xxicon.poker.message.C0300_RoomSyncResp(this);
      int from_bitField0_ = bitField0_;
      result.ownerId_ = ownerId_;
      result.roomId_ = roomId_;
      if (infosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          infos_ = java.util.Collections.unmodifiableList(infos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.infos_ = infos_;
      } else {
        result.infos_ = infosBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xxicon.poker.message.C0300_RoomSyncResp) {
        return mergeFrom((com.xxicon.poker.message.C0300_RoomSyncResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xxicon.poker.message.C0300_RoomSyncResp other) {
      if (other == com.xxicon.poker.message.C0300_RoomSyncResp.getDefaultInstance()) return this;
      if (other.getOwnerId() != 0) {
        setOwnerId(other.getOwnerId());
      }
      if (other.getRoomId() != 0) {
        setRoomId(other.getRoomId());
      }
      if (infosBuilder_ == null) {
        if (!other.infos_.isEmpty()) {
          if (infos_.isEmpty()) {
            infos_ = other.infos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInfosIsMutable();
            infos_.addAll(other.infos_);
          }
          onChanged();
        }
      } else {
        if (!other.infos_.isEmpty()) {
          if (infosBuilder_.isEmpty()) {
            infosBuilder_.dispose();
            infosBuilder_ = null;
            infos_ = other.infos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            infosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInfosFieldBuilder() : null;
          } else {
            infosBuilder_.addAllMessages(other.infos_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xxicon.poker.message.C0300_RoomSyncResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xxicon.poker.message.C0300_RoomSyncResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int ownerId_ ;
    /**
     * <pre>
     * 房主角色ID
     * </pre>
     *
     * <code>int32 ownerId = 1;</code>
     * @return The ownerId.
     */
    public int getOwnerId() {
      return ownerId_;
    }
    /**
     * <pre>
     * 房主角色ID
     * </pre>
     *
     * <code>int32 ownerId = 1;</code>
     * @param value The ownerId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerId(int value) {
      
      ownerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 房主角色ID
     * </pre>
     *
     * <code>int32 ownerId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerId() {
      
      ownerId_ = 0;
      onChanged();
      return this;
    }

    private int roomId_ ;
    /**
     * <code>int32 roomId = 2;</code>
     * @return The roomId.
     */
    public int getRoomId() {
      return roomId_;
    }
    /**
     * <code>int32 roomId = 2;</code>
     * @param value The roomId to set.
     * @return This builder for chaining.
     */
    public Builder setRoomId(int value) {
      
      roomId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 roomId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomId() {
      
      roomId_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.xxicon.poker.message.RoomRoleInfo> infos_ =
      java.util.Collections.emptyList();
    private void ensureInfosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        infos_ = new java.util.ArrayList<com.xxicon.poker.message.RoomRoleInfo>(infos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xxicon.poker.message.RoomRoleInfo, com.xxicon.poker.message.RoomRoleInfo.Builder, com.xxicon.poker.message.RoomRoleInfoOrBuilder> infosBuilder_;

    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public java.util.List<com.xxicon.poker.message.RoomRoleInfo> getInfosList() {
      if (infosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(infos_);
      } else {
        return infosBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public int getInfosCount() {
      if (infosBuilder_ == null) {
        return infos_.size();
      } else {
        return infosBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public com.xxicon.poker.message.RoomRoleInfo getInfos(int index) {
      if (infosBuilder_ == null) {
        return infos_.get(index);
      } else {
        return infosBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public Builder setInfos(
        int index, com.xxicon.poker.message.RoomRoleInfo value) {
      if (infosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfosIsMutable();
        infos_.set(index, value);
        onChanged();
      } else {
        infosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public Builder setInfos(
        int index, com.xxicon.poker.message.RoomRoleInfo.Builder builderForValue) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.set(index, builderForValue.build());
        onChanged();
      } else {
        infosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public Builder addInfos(com.xxicon.poker.message.RoomRoleInfo value) {
      if (infosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfosIsMutable();
        infos_.add(value);
        onChanged();
      } else {
        infosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public Builder addInfos(
        int index, com.xxicon.poker.message.RoomRoleInfo value) {
      if (infosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfosIsMutable();
        infos_.add(index, value);
        onChanged();
      } else {
        infosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public Builder addInfos(
        com.xxicon.poker.message.RoomRoleInfo.Builder builderForValue) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.add(builderForValue.build());
        onChanged();
      } else {
        infosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public Builder addInfos(
        int index, com.xxicon.poker.message.RoomRoleInfo.Builder builderForValue) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.add(index, builderForValue.build());
        onChanged();
      } else {
        infosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public Builder addAllInfos(
        java.lang.Iterable<? extends com.xxicon.poker.message.RoomRoleInfo> values) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, infos_);
        onChanged();
      } else {
        infosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public Builder clearInfos() {
      if (infosBuilder_ == null) {
        infos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        infosBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public Builder removeInfos(int index) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.remove(index);
        onChanged();
      } else {
        infosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public com.xxicon.poker.message.RoomRoleInfo.Builder getInfosBuilder(
        int index) {
      return getInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public com.xxicon.poker.message.RoomRoleInfoOrBuilder getInfosOrBuilder(
        int index) {
      if (infosBuilder_ == null) {
        return infos_.get(index);  } else {
        return infosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public java.util.List<? extends com.xxicon.poker.message.RoomRoleInfoOrBuilder> 
         getInfosOrBuilderList() {
      if (infosBuilder_ != null) {
        return infosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(infos_);
      }
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public com.xxicon.poker.message.RoomRoleInfo.Builder addInfosBuilder() {
      return getInfosFieldBuilder().addBuilder(
          com.xxicon.poker.message.RoomRoleInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public com.xxicon.poker.message.RoomRoleInfo.Builder addInfosBuilder(
        int index) {
      return getInfosFieldBuilder().addBuilder(
          index, com.xxicon.poker.message.RoomRoleInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
     */
    public java.util.List<com.xxicon.poker.message.RoomRoleInfo.Builder> 
         getInfosBuilderList() {
      return getInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xxicon.poker.message.RoomRoleInfo, com.xxicon.poker.message.RoomRoleInfo.Builder, com.xxicon.poker.message.RoomRoleInfoOrBuilder> 
        getInfosFieldBuilder() {
      if (infosBuilder_ == null) {
        infosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.xxicon.poker.message.RoomRoleInfo, com.xxicon.poker.message.RoomRoleInfo.Builder, com.xxicon.poker.message.RoomRoleInfoOrBuilder>(
                infos_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        infos_ = null;
      }
      return infosBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:messages.C0300_RoomSyncResp)
  }

  // @@protoc_insertion_point(class_scope:messages.C0300_RoomSyncResp)
  private static final com.xxicon.poker.message.C0300_RoomSyncResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xxicon.poker.message.C0300_RoomSyncResp();
  }

  public static com.xxicon.poker.message.C0300_RoomSyncResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<C0300_RoomSyncResp>
      PARSER = new com.google.protobuf.AbstractParser<C0300_RoomSyncResp>() {
    @java.lang.Override
    public C0300_RoomSyncResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new C0300_RoomSyncResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<C0300_RoomSyncResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<C0300_RoomSyncResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xxicon.poker.message.C0300_RoomSyncResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

