// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

public interface C0302_RoomEnterRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0302_RoomEnterResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>.messages.RoomRoleInfo role = 1;</code>
   * @return Whether the role field is set.
   */
  boolean hasRole();
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>.messages.RoomRoleInfo role = 1;</code>
   * @return The role.
   */
  com.xxicon.poker.message.RoomRoleInfo getRole();
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>.messages.RoomRoleInfo role = 1;</code>
   */
  com.xxicon.poker.message.RoomRoleInfoOrBuilder getRoleOrBuilder();
}
