// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

/**
 * Protobuf type {@code messages.C0302_RoomEnterResp}
 */
public  final class C0302_RoomEnterResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:messages.C0302_RoomEnterResp)
    C0302_RoomEnterRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use C0302_RoomEnterResp.newBuilder() to construct.
  private C0302_RoomEnterResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private C0302_RoomEnterResp() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new C0302_RoomEnterResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private C0302_RoomEnterResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.xxicon.poker.message.RoomRoleInfo.Builder subBuilder = null;
            if (role_ != null) {
              subBuilder = role_.toBuilder();
            }
            role_ = input.readMessage(com.xxicon.poker.message.RoomRoleInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(role_);
              role_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xxicon.poker.message.Room.internal_static_messages_C0302_RoomEnterResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xxicon.poker.message.Room.internal_static_messages_C0302_RoomEnterResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xxicon.poker.message.C0302_RoomEnterResp.class, com.xxicon.poker.message.C0302_RoomEnterResp.Builder.class);
  }

  public static final int ROLE_FIELD_NUMBER = 1;
  private com.xxicon.poker.message.RoomRoleInfo role_;
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>.messages.RoomRoleInfo role = 1;</code>
   * @return Whether the role field is set.
   */
  public boolean hasRole() {
    return role_ != null;
  }
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>.messages.RoomRoleInfo role = 1;</code>
   * @return The role.
   */
  public com.xxicon.poker.message.RoomRoleInfo getRole() {
    return role_ == null ? com.xxicon.poker.message.RoomRoleInfo.getDefaultInstance() : role_;
  }
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>.messages.RoomRoleInfo role = 1;</code>
   */
  public com.xxicon.poker.message.RoomRoleInfoOrBuilder getRoleOrBuilder() {
    return getRole();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (role_ != null) {
      output.writeMessage(1, getRole());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (role_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRole());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xxicon.poker.message.C0302_RoomEnterResp)) {
      return super.equals(obj);
    }
    com.xxicon.poker.message.C0302_RoomEnterResp other = (com.xxicon.poker.message.C0302_RoomEnterResp) obj;

    if (hasRole() != other.hasRole()) return false;
    if (hasRole()) {
      if (!getRole()
          .equals(other.getRole())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRole()) {
      hash = (37 * hash) + ROLE_FIELD_NUMBER;
      hash = (53 * hash) + getRole().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xxicon.poker.message.C0302_RoomEnterResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxicon.poker.message.C0302_RoomEnterResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0302_RoomEnterResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxicon.poker.message.C0302_RoomEnterResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0302_RoomEnterResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxicon.poker.message.C0302_RoomEnterResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0302_RoomEnterResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xxicon.poker.message.C0302_RoomEnterResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0302_RoomEnterResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xxicon.poker.message.C0302_RoomEnterResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0302_RoomEnterResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xxicon.poker.message.C0302_RoomEnterResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xxicon.poker.message.C0302_RoomEnterResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code messages.C0302_RoomEnterResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:messages.C0302_RoomEnterResp)
      com.xxicon.poker.message.C0302_RoomEnterRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xxicon.poker.message.Room.internal_static_messages_C0302_RoomEnterResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xxicon.poker.message.Room.internal_static_messages_C0302_RoomEnterResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xxicon.poker.message.C0302_RoomEnterResp.class, com.xxicon.poker.message.C0302_RoomEnterResp.Builder.class);
    }

    // Construct using com.xxicon.poker.message.C0302_RoomEnterResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (roleBuilder_ == null) {
        role_ = null;
      } else {
        role_ = null;
        roleBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xxicon.poker.message.Room.internal_static_messages_C0302_RoomEnterResp_descriptor;
    }

    @java.lang.Override
    public com.xxicon.poker.message.C0302_RoomEnterResp getDefaultInstanceForType() {
      return com.xxicon.poker.message.C0302_RoomEnterResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.xxicon.poker.message.C0302_RoomEnterResp build() {
      com.xxicon.poker.message.C0302_RoomEnterResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xxicon.poker.message.C0302_RoomEnterResp buildPartial() {
      com.xxicon.poker.message.C0302_RoomEnterResp result = new com.xxicon.poker.message.C0302_RoomEnterResp(this);
      if (roleBuilder_ == null) {
        result.role_ = role_;
      } else {
        result.role_ = roleBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xxicon.poker.message.C0302_RoomEnterResp) {
        return mergeFrom((com.xxicon.poker.message.C0302_RoomEnterResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xxicon.poker.message.C0302_RoomEnterResp other) {
      if (other == com.xxicon.poker.message.C0302_RoomEnterResp.getDefaultInstance()) return this;
      if (other.hasRole()) {
        mergeRole(other.getRole());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xxicon.poker.message.C0302_RoomEnterResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xxicon.poker.message.C0302_RoomEnterResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.xxicon.poker.message.RoomRoleInfo role_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xxicon.poker.message.RoomRoleInfo, com.xxicon.poker.message.RoomRoleInfo.Builder, com.xxicon.poker.message.RoomRoleInfoOrBuilder> roleBuilder_;
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo role = 1;</code>
     * @return Whether the role field is set.
     */
    public boolean hasRole() {
      return roleBuilder_ != null || role_ != null;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo role = 1;</code>
     * @return The role.
     */
    public com.xxicon.poker.message.RoomRoleInfo getRole() {
      if (roleBuilder_ == null) {
        return role_ == null ? com.xxicon.poker.message.RoomRoleInfo.getDefaultInstance() : role_;
      } else {
        return roleBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo role = 1;</code>
     */
    public Builder setRole(com.xxicon.poker.message.RoomRoleInfo value) {
      if (roleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        role_ = value;
        onChanged();
      } else {
        roleBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo role = 1;</code>
     */
    public Builder setRole(
        com.xxicon.poker.message.RoomRoleInfo.Builder builderForValue) {
      if (roleBuilder_ == null) {
        role_ = builderForValue.build();
        onChanged();
      } else {
        roleBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo role = 1;</code>
     */
    public Builder mergeRole(com.xxicon.poker.message.RoomRoleInfo value) {
      if (roleBuilder_ == null) {
        if (role_ != null) {
          role_ =
            com.xxicon.poker.message.RoomRoleInfo.newBuilder(role_).mergeFrom(value).buildPartial();
        } else {
          role_ = value;
        }
        onChanged();
      } else {
        roleBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo role = 1;</code>
     */
    public Builder clearRole() {
      if (roleBuilder_ == null) {
        role_ = null;
        onChanged();
      } else {
        role_ = null;
        roleBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo role = 1;</code>
     */
    public com.xxicon.poker.message.RoomRoleInfo.Builder getRoleBuilder() {
      
      onChanged();
      return getRoleFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo role = 1;</code>
     */
    public com.xxicon.poker.message.RoomRoleInfoOrBuilder getRoleOrBuilder() {
      if (roleBuilder_ != null) {
        return roleBuilder_.getMessageOrBuilder();
      } else {
        return role_ == null ?
            com.xxicon.poker.message.RoomRoleInfo.getDefaultInstance() : role_;
      }
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo role = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xxicon.poker.message.RoomRoleInfo, com.xxicon.poker.message.RoomRoleInfo.Builder, com.xxicon.poker.message.RoomRoleInfoOrBuilder> 
        getRoleFieldBuilder() {
      if (roleBuilder_ == null) {
        roleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xxicon.poker.message.RoomRoleInfo, com.xxicon.poker.message.RoomRoleInfo.Builder, com.xxicon.poker.message.RoomRoleInfoOrBuilder>(
                getRole(),
                getParentForChildren(),
                isClean());
        role_ = null;
      }
      return roleBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:messages.C0302_RoomEnterResp)
  }

  // @@protoc_insertion_point(class_scope:messages.C0302_RoomEnterResp)
  private static final com.xxicon.poker.message.C0302_RoomEnterResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xxicon.poker.message.C0302_RoomEnterResp();
  }

  public static com.xxicon.poker.message.C0302_RoomEnterResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<C0302_RoomEnterResp>
      PARSER = new com.google.protobuf.AbstractParser<C0302_RoomEnterResp>() {
    @java.lang.Override
    public C0302_RoomEnterResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new C0302_RoomEnterResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<C0302_RoomEnterResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<C0302_RoomEnterResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xxicon.poker.message.C0302_RoomEnterResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

