// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

public interface C0303_RoomCreateReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0303_RoomCreateReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 房间密码
   * </pre>
   *
   * <code>string password = 1;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <pre>
   * 房间密码
   * </pre>
   *
   * <code>string password = 1;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
