// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

public interface C0301_RoomMatchReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0301_RoomMatchReq)
    com.google.protobuf.MessageOrBuilder {
}
