// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

public interface C0300_RoomSyncRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0300_RoomSyncResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 房主角色ID
   * </pre>
   *
   * <code>int32 ownerId = 1;</code>
   * @return The ownerId.
   */
  int getOwnerId();

  /**
   * <code>int32 roomId = 2;</code>
   * @return The roomId.
   */
  int getRoomId();

  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
   */
  java.util.List<com.xxicon.poker.message.RoomRoleInfo> 
      getInfosList();
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
   */
  com.xxicon.poker.message.RoomRoleInfo getInfos(int index);
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
   */
  int getInfosCount();
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
   */
  java.util.List<? extends com.xxicon.poker.message.RoomRoleInfoOrBuilder> 
      getInfosOrBuilderList();
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>repeated .messages.RoomRoleInfo infos = 3;</code>
   */
  com.xxicon.poker.message.RoomRoleInfoOrBuilder getInfosOrBuilder(
      int index);
}
