// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

public interface C0304_RoomLeaveReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0304_RoomLeaveReq)
    com.google.protobuf.MessageOrBuilder {
}
