// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

public interface C0304_RoomLeaveRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0304_RoomLeaveResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 roleId = 1;</code>
   * @return The roleId.
   */
  int getRoleId();
}
