// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

public interface C0312_RoomStateGoReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0312_RoomStateGoReq)
    com.google.protobuf.MessageOrBuilder {
}
