// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

public interface C0310_RoomStateReadyReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0310_RoomStateReadyReq)
    com.google.protobuf.MessageOrBuilder {
}
