// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

public interface C0313_RoomRoleSyncRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0313_RoomRoleSyncResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 房主角色ID
   * </pre>
   *
   * <code>int32 ownerId = 1;</code>
   * @return The ownerId.
   */
  int getOwnerId();

  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>.messages.RoomRoleInfo roleInfo = 2;</code>
   * @return Whether the roleInfo field is set.
   */
  boolean hasRoleInfo();
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>.messages.RoomRoleInfo roleInfo = 2;</code>
   * @return The roleInfo.
   */
  com.xxicon.poker.message.RoomRoleInfo getRoleInfo();
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>.messages.RoomRoleInfo roleInfo = 2;</code>
   */
  com.xxicon.poker.message.RoomRoleInfoOrBuilder getRoleInfoOrBuilder();
}
