// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

/**
 * Protobuf type {@code messages.C0313_RoomRoleSyncResp}
 */
public  final class C0313_RoomRoleSyncResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:messages.C0313_RoomRoleSyncResp)
    C0313_RoomRoleSyncRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use C0313_RoomRoleSyncResp.newBuilder() to construct.
  private C0313_RoomRoleSyncResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private C0313_RoomRoleSyncResp() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new C0313_RoomRoleSyncResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private C0313_RoomRoleSyncResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            ownerId_ = input.readInt32();
            break;
          }
          case 18: {
            com.xxicon.poker.message.RoomRoleInfo.Builder subBuilder = null;
            if (roleInfo_ != null) {
              subBuilder = roleInfo_.toBuilder();
            }
            roleInfo_ = input.readMessage(com.xxicon.poker.message.RoomRoleInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(roleInfo_);
              roleInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xxicon.poker.message.Room.internal_static_messages_C0313_RoomRoleSyncResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xxicon.poker.message.Room.internal_static_messages_C0313_RoomRoleSyncResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xxicon.poker.message.C0313_RoomRoleSyncResp.class, com.xxicon.poker.message.C0313_RoomRoleSyncResp.Builder.class);
  }

  public static final int OWNERID_FIELD_NUMBER = 1;
  private int ownerId_;
  /**
   * <pre>
   * 房主角色ID
   * </pre>
   *
   * <code>int32 ownerId = 1;</code>
   * @return The ownerId.
   */
  public int getOwnerId() {
    return ownerId_;
  }

  public static final int ROLEINFO_FIELD_NUMBER = 2;
  private com.xxicon.poker.message.RoomRoleInfo roleInfo_;
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>.messages.RoomRoleInfo roleInfo = 2;</code>
   * @return Whether the roleInfo field is set.
   */
  public boolean hasRoleInfo() {
    return roleInfo_ != null;
  }
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>.messages.RoomRoleInfo roleInfo = 2;</code>
   * @return The roleInfo.
   */
  public com.xxicon.poker.message.RoomRoleInfo getRoleInfo() {
    return roleInfo_ == null ? com.xxicon.poker.message.RoomRoleInfo.getDefaultInstance() : roleInfo_;
  }
  /**
   * <pre>
   * 房间角色
   * </pre>
   *
   * <code>.messages.RoomRoleInfo roleInfo = 2;</code>
   */
  public com.xxicon.poker.message.RoomRoleInfoOrBuilder getRoleInfoOrBuilder() {
    return getRoleInfo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ownerId_ != 0) {
      output.writeInt32(1, ownerId_);
    }
    if (roleInfo_ != null) {
      output.writeMessage(2, getRoleInfo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ownerId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ownerId_);
    }
    if (roleInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRoleInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xxicon.poker.message.C0313_RoomRoleSyncResp)) {
      return super.equals(obj);
    }
    com.xxicon.poker.message.C0313_RoomRoleSyncResp other = (com.xxicon.poker.message.C0313_RoomRoleSyncResp) obj;

    if (getOwnerId()
        != other.getOwnerId()) return false;
    if (hasRoleInfo() != other.hasRoleInfo()) return false;
    if (hasRoleInfo()) {
      if (!getRoleInfo()
          .equals(other.getRoleInfo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OWNERID_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerId();
    if (hasRoleInfo()) {
      hash = (37 * hash) + ROLEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getRoleInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xxicon.poker.message.C0313_RoomRoleSyncResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxicon.poker.message.C0313_RoomRoleSyncResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0313_RoomRoleSyncResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxicon.poker.message.C0313_RoomRoleSyncResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0313_RoomRoleSyncResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxicon.poker.message.C0313_RoomRoleSyncResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0313_RoomRoleSyncResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xxicon.poker.message.C0313_RoomRoleSyncResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0313_RoomRoleSyncResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xxicon.poker.message.C0313_RoomRoleSyncResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0313_RoomRoleSyncResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xxicon.poker.message.C0313_RoomRoleSyncResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xxicon.poker.message.C0313_RoomRoleSyncResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code messages.C0313_RoomRoleSyncResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:messages.C0313_RoomRoleSyncResp)
      com.xxicon.poker.message.C0313_RoomRoleSyncRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xxicon.poker.message.Room.internal_static_messages_C0313_RoomRoleSyncResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xxicon.poker.message.Room.internal_static_messages_C0313_RoomRoleSyncResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xxicon.poker.message.C0313_RoomRoleSyncResp.class, com.xxicon.poker.message.C0313_RoomRoleSyncResp.Builder.class);
    }

    // Construct using com.xxicon.poker.message.C0313_RoomRoleSyncResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ownerId_ = 0;

      if (roleInfoBuilder_ == null) {
        roleInfo_ = null;
      } else {
        roleInfo_ = null;
        roleInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xxicon.poker.message.Room.internal_static_messages_C0313_RoomRoleSyncResp_descriptor;
    }

    @java.lang.Override
    public com.xxicon.poker.message.C0313_RoomRoleSyncResp getDefaultInstanceForType() {
      return com.xxicon.poker.message.C0313_RoomRoleSyncResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.xxicon.poker.message.C0313_RoomRoleSyncResp build() {
      com.xxicon.poker.message.C0313_RoomRoleSyncResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xxicon.poker.message.C0313_RoomRoleSyncResp buildPartial() {
      com.xxicon.poker.message.C0313_RoomRoleSyncResp result = new com.xxicon.poker.message.C0313_RoomRoleSyncResp(this);
      result.ownerId_ = ownerId_;
      if (roleInfoBuilder_ == null) {
        result.roleInfo_ = roleInfo_;
      } else {
        result.roleInfo_ = roleInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xxicon.poker.message.C0313_RoomRoleSyncResp) {
        return mergeFrom((com.xxicon.poker.message.C0313_RoomRoleSyncResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xxicon.poker.message.C0313_RoomRoleSyncResp other) {
      if (other == com.xxicon.poker.message.C0313_RoomRoleSyncResp.getDefaultInstance()) return this;
      if (other.getOwnerId() != 0) {
        setOwnerId(other.getOwnerId());
      }
      if (other.hasRoleInfo()) {
        mergeRoleInfo(other.getRoleInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xxicon.poker.message.C0313_RoomRoleSyncResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xxicon.poker.message.C0313_RoomRoleSyncResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int ownerId_ ;
    /**
     * <pre>
     * 房主角色ID
     * </pre>
     *
     * <code>int32 ownerId = 1;</code>
     * @return The ownerId.
     */
    public int getOwnerId() {
      return ownerId_;
    }
    /**
     * <pre>
     * 房主角色ID
     * </pre>
     *
     * <code>int32 ownerId = 1;</code>
     * @param value The ownerId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerId(int value) {
      
      ownerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 房主角色ID
     * </pre>
     *
     * <code>int32 ownerId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerId() {
      
      ownerId_ = 0;
      onChanged();
      return this;
    }

    private com.xxicon.poker.message.RoomRoleInfo roleInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xxicon.poker.message.RoomRoleInfo, com.xxicon.poker.message.RoomRoleInfo.Builder, com.xxicon.poker.message.RoomRoleInfoOrBuilder> roleInfoBuilder_;
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo roleInfo = 2;</code>
     * @return Whether the roleInfo field is set.
     */
    public boolean hasRoleInfo() {
      return roleInfoBuilder_ != null || roleInfo_ != null;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo roleInfo = 2;</code>
     * @return The roleInfo.
     */
    public com.xxicon.poker.message.RoomRoleInfo getRoleInfo() {
      if (roleInfoBuilder_ == null) {
        return roleInfo_ == null ? com.xxicon.poker.message.RoomRoleInfo.getDefaultInstance() : roleInfo_;
      } else {
        return roleInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo roleInfo = 2;</code>
     */
    public Builder setRoleInfo(com.xxicon.poker.message.RoomRoleInfo value) {
      if (roleInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        roleInfo_ = value;
        onChanged();
      } else {
        roleInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo roleInfo = 2;</code>
     */
    public Builder setRoleInfo(
        com.xxicon.poker.message.RoomRoleInfo.Builder builderForValue) {
      if (roleInfoBuilder_ == null) {
        roleInfo_ = builderForValue.build();
        onChanged();
      } else {
        roleInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo roleInfo = 2;</code>
     */
    public Builder mergeRoleInfo(com.xxicon.poker.message.RoomRoleInfo value) {
      if (roleInfoBuilder_ == null) {
        if (roleInfo_ != null) {
          roleInfo_ =
            com.xxicon.poker.message.RoomRoleInfo.newBuilder(roleInfo_).mergeFrom(value).buildPartial();
        } else {
          roleInfo_ = value;
        }
        onChanged();
      } else {
        roleInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo roleInfo = 2;</code>
     */
    public Builder clearRoleInfo() {
      if (roleInfoBuilder_ == null) {
        roleInfo_ = null;
        onChanged();
      } else {
        roleInfo_ = null;
        roleInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo roleInfo = 2;</code>
     */
    public com.xxicon.poker.message.RoomRoleInfo.Builder getRoleInfoBuilder() {
      
      onChanged();
      return getRoleInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo roleInfo = 2;</code>
     */
    public com.xxicon.poker.message.RoomRoleInfoOrBuilder getRoleInfoOrBuilder() {
      if (roleInfoBuilder_ != null) {
        return roleInfoBuilder_.getMessageOrBuilder();
      } else {
        return roleInfo_ == null ?
            com.xxicon.poker.message.RoomRoleInfo.getDefaultInstance() : roleInfo_;
      }
    }
    /**
     * <pre>
     * 房间角色
     * </pre>
     *
     * <code>.messages.RoomRoleInfo roleInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xxicon.poker.message.RoomRoleInfo, com.xxicon.poker.message.RoomRoleInfo.Builder, com.xxicon.poker.message.RoomRoleInfoOrBuilder> 
        getRoleInfoFieldBuilder() {
      if (roleInfoBuilder_ == null) {
        roleInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xxicon.poker.message.RoomRoleInfo, com.xxicon.poker.message.RoomRoleInfo.Builder, com.xxicon.poker.message.RoomRoleInfoOrBuilder>(
                getRoleInfo(),
                getParentForChildren(),
                isClean());
        roleInfo_ = null;
      }
      return roleInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:messages.C0313_RoomRoleSyncResp)
  }

  // @@protoc_insertion_point(class_scope:messages.C0313_RoomRoleSyncResp)
  private static final com.xxicon.poker.message.C0313_RoomRoleSyncResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xxicon.poker.message.C0313_RoomRoleSyncResp();
  }

  public static com.xxicon.poker.message.C0313_RoomRoleSyncResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<C0313_RoomRoleSyncResp>
      PARSER = new com.google.protobuf.AbstractParser<C0313_RoomRoleSyncResp>() {
    @java.lang.Override
    public C0313_RoomRoleSyncResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new C0313_RoomRoleSyncResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<C0313_RoomRoleSyncResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<C0313_RoomRoleSyncResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xxicon.poker.message.C0313_RoomRoleSyncResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

