// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

public interface C0312_RoomStateGoRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0312_RoomStateGoResp)
    com.google.protobuf.MessageOrBuilder {
}
