// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

public interface C0311_RoomStateCancelReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0311_RoomStateCancelReq)
    com.google.protobuf.MessageOrBuilder {
}
