// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/poker.proto

package com.xxicon.poker.message;

/**
 * Protobuf type {@code messages.C0402_PokerInvestMoneyResp}
 */
public  final class C0402_PokerInvestMoneyResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:messages.C0402_PokerInvestMoneyResp)
    C0402_PokerInvestMoneyRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use C0402_PokerInvestMoneyResp.newBuilder() to construct.
  private C0402_PokerInvestMoneyResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private C0402_PokerInvestMoneyResp() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new C0402_PokerInvestMoneyResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private C0402_PokerInvestMoneyResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            money_ = input.readInt32();
            break;
          }
          case 16: {

            turn_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xxicon.poker.message.Poker.internal_static_messages_C0402_PokerInvestMoneyResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xxicon.poker.message.Poker.internal_static_messages_C0402_PokerInvestMoneyResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xxicon.poker.message.C0402_PokerInvestMoneyResp.class, com.xxicon.poker.message.C0402_PokerInvestMoneyResp.Builder.class);
  }

  public static final int MONEY_FIELD_NUMBER = 1;
  private int money_;
  /**
   * <code>int32 money = 1;</code>
   * @return The money.
   */
  public int getMoney() {
    return money_;
  }

  public static final int TURN_FIELD_NUMBER = 2;
  private int turn_;
  /**
   * <code>int32 turn = 2;</code>
   * @return The turn.
   */
  public int getTurn() {
    return turn_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (money_ != 0) {
      output.writeInt32(1, money_);
    }
    if (turn_ != 0) {
      output.writeInt32(2, turn_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (money_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, money_);
    }
    if (turn_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, turn_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xxicon.poker.message.C0402_PokerInvestMoneyResp)) {
      return super.equals(obj);
    }
    com.xxicon.poker.message.C0402_PokerInvestMoneyResp other = (com.xxicon.poker.message.C0402_PokerInvestMoneyResp) obj;

    if (getMoney()
        != other.getMoney()) return false;
    if (getTurn()
        != other.getTurn()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MONEY_FIELD_NUMBER;
    hash = (53 * hash) + getMoney();
    hash = (37 * hash) + TURN_FIELD_NUMBER;
    hash = (53 * hash) + getTurn();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xxicon.poker.message.C0402_PokerInvestMoneyResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxicon.poker.message.C0402_PokerInvestMoneyResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0402_PokerInvestMoneyResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxicon.poker.message.C0402_PokerInvestMoneyResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0402_PokerInvestMoneyResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxicon.poker.message.C0402_PokerInvestMoneyResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0402_PokerInvestMoneyResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xxicon.poker.message.C0402_PokerInvestMoneyResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0402_PokerInvestMoneyResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xxicon.poker.message.C0402_PokerInvestMoneyResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xxicon.poker.message.C0402_PokerInvestMoneyResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xxicon.poker.message.C0402_PokerInvestMoneyResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xxicon.poker.message.C0402_PokerInvestMoneyResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code messages.C0402_PokerInvestMoneyResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:messages.C0402_PokerInvestMoneyResp)
      com.xxicon.poker.message.C0402_PokerInvestMoneyRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xxicon.poker.message.Poker.internal_static_messages_C0402_PokerInvestMoneyResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xxicon.poker.message.Poker.internal_static_messages_C0402_PokerInvestMoneyResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xxicon.poker.message.C0402_PokerInvestMoneyResp.class, com.xxicon.poker.message.C0402_PokerInvestMoneyResp.Builder.class);
    }

    // Construct using com.xxicon.poker.message.C0402_PokerInvestMoneyResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      money_ = 0;

      turn_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xxicon.poker.message.Poker.internal_static_messages_C0402_PokerInvestMoneyResp_descriptor;
    }

    @java.lang.Override
    public com.xxicon.poker.message.C0402_PokerInvestMoneyResp getDefaultInstanceForType() {
      return com.xxicon.poker.message.C0402_PokerInvestMoneyResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.xxicon.poker.message.C0402_PokerInvestMoneyResp build() {
      com.xxicon.poker.message.C0402_PokerInvestMoneyResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xxicon.poker.message.C0402_PokerInvestMoneyResp buildPartial() {
      com.xxicon.poker.message.C0402_PokerInvestMoneyResp result = new com.xxicon.poker.message.C0402_PokerInvestMoneyResp(this);
      result.money_ = money_;
      result.turn_ = turn_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xxicon.poker.message.C0402_PokerInvestMoneyResp) {
        return mergeFrom((com.xxicon.poker.message.C0402_PokerInvestMoneyResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xxicon.poker.message.C0402_PokerInvestMoneyResp other) {
      if (other == com.xxicon.poker.message.C0402_PokerInvestMoneyResp.getDefaultInstance()) return this;
      if (other.getMoney() != 0) {
        setMoney(other.getMoney());
      }
      if (other.getTurn() != 0) {
        setTurn(other.getTurn());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xxicon.poker.message.C0402_PokerInvestMoneyResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xxicon.poker.message.C0402_PokerInvestMoneyResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int money_ ;
    /**
     * <code>int32 money = 1;</code>
     * @return The money.
     */
    public int getMoney() {
      return money_;
    }
    /**
     * <code>int32 money = 1;</code>
     * @param value The money to set.
     * @return This builder for chaining.
     */
    public Builder setMoney(int value) {
      
      money_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 money = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoney() {
      
      money_ = 0;
      onChanged();
      return this;
    }

    private int turn_ ;
    /**
     * <code>int32 turn = 2;</code>
     * @return The turn.
     */
    public int getTurn() {
      return turn_;
    }
    /**
     * <code>int32 turn = 2;</code>
     * @param value The turn to set.
     * @return This builder for chaining.
     */
    public Builder setTurn(int value) {
      
      turn_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 turn = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTurn() {
      
      turn_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:messages.C0402_PokerInvestMoneyResp)
  }

  // @@protoc_insertion_point(class_scope:messages.C0402_PokerInvestMoneyResp)
  private static final com.xxicon.poker.message.C0402_PokerInvestMoneyResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xxicon.poker.message.C0402_PokerInvestMoneyResp();
  }

  public static com.xxicon.poker.message.C0402_PokerInvestMoneyResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<C0402_PokerInvestMoneyResp>
      PARSER = new com.google.protobuf.AbstractParser<C0402_PokerInvestMoneyResp>() {
    @java.lang.Override
    public C0402_PokerInvestMoneyResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new C0402_PokerInvestMoneyResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<C0402_PokerInvestMoneyResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<C0402_PokerInvestMoneyResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xxicon.poker.message.C0402_PokerInvestMoneyResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

