// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/poker.proto

package com.xxicon.poker.message;

public interface C0400_PokerSendRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0400_PokerSendResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 牌 0-51
   * </pre>
   *
   * <code>repeated int32 pokers = 1;</code>
   * @return A list containing the pokers.
   */
  java.util.List<java.lang.Integer> getPokersList();
  /**
   * <pre>
   * 牌 0-51
   * </pre>
   *
   * <code>repeated int32 pokers = 1;</code>
   * @return The count of pokers.
   */
  int getPokersCount();
  /**
   * <pre>
   * 牌 0-51
   * </pre>
   *
   * <code>repeated int32 pokers = 1;</code>
   * @param index The index of the element to return.
   * @return The pokers at the given index.
   */
  int getPokers(int index);

  /**
   * <pre>
   * 第一个出牌位置（房间位置）
   * </pre>
   *
   * <code>int32 first = 2;</code>
   * @return The first.
   */
  int getFirst();
}
