// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/poker.proto

package com.xxicon.poker.message;

public interface C0401_PokerBattleReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0401_PokerBattleReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 开牌对手
   * </pre>
   *
   * <code>int32 rival = 1;</code>
   * @return The rival.
   */
  int getRival();
}
