// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/poker.proto

package com.xxicon.poker.message;

public interface C0403_PokerAdmitDefeatRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0403_PokerAdmitDefeatResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 loser = 1;</code>
   * @return The loser.
   */
  int getLoser();

  /**
   * <code>int32 turn = 2;</code>
   * @return The turn.
   */
  int getTurn();
}
