// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/poker.proto

package com.xxicon.poker.message;

public interface C0403_PokerAdmitDefeatReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0403_PokerAdmitDefeatReq)
    com.google.protobuf.MessageOrBuilder {
}
