// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/poker.proto

package com.xxicon.poker.message;

public interface C0404_PokerGameOverRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0404_PokerGameOverResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 victor = 1;</code>
   * @return The victor.
   */
  int getVictor();
}
