// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/poker.proto

package com.xxicon.poker.message;

public interface C0402_PokerInvestMoneyReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.C0402_PokerInvestMoneyReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 money = 1;</code>
   * @return The money.
   */
  int getMoney();
}
