// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/chat.proto

package com.xxicon.poker.message;

public interface ChatInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.ChatInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 roleId = 1;</code>
   * @return The roleId.
   */
  int getRoleId();

  /**
   * <code>string roleName = 2;</code>
   * @return The roleName.
   */
  java.lang.String getRoleName();
  /**
   * <code>string roleName = 2;</code>
   * @return The bytes for roleName.
   */
  com.google.protobuf.ByteString
      getRoleNameBytes();

  /**
   * <code>int32 roleLevel = 3;</code>
   * @return The roleLevel.
   */
  int getRoleLevel();

  /**
   * <pre>
   * 聊天内容
   * </pre>
   *
   * <code>string content = 4;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 聊天内容
   * </pre>
   *
   * <code>string content = 4;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
