// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/base.proto

package com.xxicon.poker.message;

public interface HeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.Header)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
