// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/poker.proto

package com.xxicon.poker.message;

public final class Poker {
  private Poker() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_C0400_PokerSendResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_C0400_PokerSendResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_C0401_PokerBattleReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_C0401_PokerBattleReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_C0401_PokerBattleResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_C0401_PokerBattleResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_C0402_PokerInvestMoneyReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_C0402_PokerInvestMoneyReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_C0402_PokerInvestMoneyResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_C0402_PokerInvestMoneyResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_C0403_PokerAdmitDefeatReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_C0403_PokerAdmitDefeatReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_C0403_PokerAdmitDefeatResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_C0403_PokerAdmitDefeatResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_C0404_PokerGameOverResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_C0404_PokerGameOverResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/poker.proto\022\010messages\"4\n\023C0400_P" +
      "okerSendResp\022\016\n\006pokers\030\001 \003(\005\022\r\n\005first\030\002 " +
      "\001(\005\"%\n\024C0401_PokerBattleReq\022\r\n\005rival\030\001 \001" +
      "(\005\"4\n\025C0401_PokerBattleResp\022\r\n\005loser\030\001 \001" +
      "(\005\022\014\n\004turn\030\002 \001(\005\"*\n\031C0402_PokerInvestMon" +
      "eyReq\022\r\n\005money\030\001 \001(\005\"9\n\032C0402_PokerInves" +
      "tMoneyResp\022\r\n\005money\030\001 \001(\005\022\014\n\004turn\030\002 \001(\005\"" +
      "\033\n\031C0403_PokerAdmitDefeatReq\"9\n\032C0403_Po" +
      "kerAdmitDefeatResp\022\r\n\005loser\030\001 \001(\005\022\014\n\004tur" +
      "n\030\002 \001(\005\")\n\027C0404_PokerGameOverResp\022\016\n\006vi" +
      "ctor\030\001 \001(\005B\034\n\030com.xxicon.poker.messageP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_messages_C0400_PokerSendResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_C0400_PokerSendResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_C0400_PokerSendResp_descriptor,
        new java.lang.String[] { "Pokers", "First", });
    internal_static_messages_C0401_PokerBattleReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_messages_C0401_PokerBattleReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_C0401_PokerBattleReq_descriptor,
        new java.lang.String[] { "Rival", });
    internal_static_messages_C0401_PokerBattleResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_messages_C0401_PokerBattleResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_C0401_PokerBattleResp_descriptor,
        new java.lang.String[] { "Loser", "Turn", });
    internal_static_messages_C0402_PokerInvestMoneyReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_messages_C0402_PokerInvestMoneyReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_C0402_PokerInvestMoneyReq_descriptor,
        new java.lang.String[] { "Money", });
    internal_static_messages_C0402_PokerInvestMoneyResp_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_messages_C0402_PokerInvestMoneyResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_C0402_PokerInvestMoneyResp_descriptor,
        new java.lang.String[] { "Money", "Turn", });
    internal_static_messages_C0403_PokerAdmitDefeatReq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_messages_C0403_PokerAdmitDefeatReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_C0403_PokerAdmitDefeatReq_descriptor,
        new java.lang.String[] { });
    internal_static_messages_C0403_PokerAdmitDefeatResp_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_messages_C0403_PokerAdmitDefeatResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_C0403_PokerAdmitDefeatResp_descriptor,
        new java.lang.String[] { "Loser", "Turn", });
    internal_static_messages_C0404_PokerGameOverResp_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_messages_C0404_PokerGameOverResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_C0404_PokerGameOverResp_descriptor,
        new java.lang.String[] { "Victor", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
