// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/role.proto

package com.xxicon.poker.message;

public interface RoleInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.RoleInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 角色ID
   * </pre>
   *
   * <code>int32 roleId = 1;</code>
   * @return The roleId.
   */
  int getRoleId();

  /**
   * <pre>
   * 角色名
   * </pre>
   *
   * <code>string roleName = 2;</code>
   * @return The roleName.
   */
  java.lang.String getRoleName();
  /**
   * <pre>
   * 角色名
   * </pre>
   *
   * <code>string roleName = 2;</code>
   * @return The bytes for roleName.
   */
  com.google.protobuf.ByteString
      getRoleNameBytes();

  /**
   * <pre>
   * 性别 0=女, 1=男
   * </pre>
   *
   * <code>int32 gender = 3;</code>
   * @return The gender.
   */
  int getGender();

  /**
   * <pre>
   * 等级
   * </pre>
   *
   * <code>int32 level = 4;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <pre>
   * 金钱数
   * </pre>
   *
   * <code>int32 money = 5;</code>
   * @return The money.
   */
  int getMoney();
}
