// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/room.proto

package com.xxicon.poker.message;

/**
 * Protobuf type {@code messages.RoomRoleInfo}
 */
public  final class RoomRoleInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:messages.RoomRoleInfo)
    RoomRoleInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RoomRoleInfo.newBuilder() to construct.
  private RoomRoleInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RoomRoleInfo() {
    roleName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RoomRoleInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RoomRoleInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            index_ = input.readInt32();
            break;
          }
          case 16: {

            roleId_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            roleName_ = s;
            break;
          }
          case 32: {

            roleLevel_ = input.readInt32();
            break;
          }
          case 40: {

            isReady_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xxicon.poker.message.Room.internal_static_messages_RoomRoleInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xxicon.poker.message.Room.internal_static_messages_RoomRoleInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xxicon.poker.message.RoomRoleInfo.class, com.xxicon.poker.message.RoomRoleInfo.Builder.class);
  }

  public static final int INDEX_FIELD_NUMBER = 1;
  private int index_;
  /**
   * <pre>
   * 房间位置
   * </pre>
   *
   * <code>int32 index = 1;</code>
   * @return The index.
   */
  public int getIndex() {
    return index_;
  }

  public static final int ROLEID_FIELD_NUMBER = 2;
  private int roleId_;
  /**
   * <code>int32 roleId = 2;</code>
   * @return The roleId.
   */
  public int getRoleId() {
    return roleId_;
  }

  public static final int ROLENAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object roleName_;
  /**
   * <code>string roleName = 3;</code>
   * @return The roleName.
   */
  public java.lang.String getRoleName() {
    java.lang.Object ref = roleName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roleName_ = s;
      return s;
    }
  }
  /**
   * <code>string roleName = 3;</code>
   * @return The bytes for roleName.
   */
  public com.google.protobuf.ByteString
      getRoleNameBytes() {
    java.lang.Object ref = roleName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roleName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROLELEVEL_FIELD_NUMBER = 4;
  private int roleLevel_;
  /**
   * <code>int32 roleLevel = 4;</code>
   * @return The roleLevel.
   */
  public int getRoleLevel() {
    return roleLevel_;
  }

  public static final int ISREADY_FIELD_NUMBER = 5;
  private int isReady_;
  /**
   * <code>int32 isReady = 5;</code>
   * @return The isReady.
   */
  public int getIsReady() {
    return isReady_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (index_ != 0) {
      output.writeInt32(1, index_);
    }
    if (roleId_ != 0) {
      output.writeInt32(2, roleId_);
    }
    if (!getRoleNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, roleName_);
    }
    if (roleLevel_ != 0) {
      output.writeInt32(4, roleLevel_);
    }
    if (isReady_ != 0) {
      output.writeInt32(5, isReady_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (index_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, index_);
    }
    if (roleId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, roleId_);
    }
    if (!getRoleNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, roleName_);
    }
    if (roleLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, roleLevel_);
    }
    if (isReady_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, isReady_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xxicon.poker.message.RoomRoleInfo)) {
      return super.equals(obj);
    }
    com.xxicon.poker.message.RoomRoleInfo other = (com.xxicon.poker.message.RoomRoleInfo) obj;

    if (getIndex()
        != other.getIndex()) return false;
    if (getRoleId()
        != other.getRoleId()) return false;
    if (!getRoleName()
        .equals(other.getRoleName())) return false;
    if (getRoleLevel()
        != other.getRoleLevel()) return false;
    if (getIsReady()
        != other.getIsReady()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getIndex();
    hash = (37 * hash) + ROLEID_FIELD_NUMBER;
    hash = (53 * hash) + getRoleId();
    hash = (37 * hash) + ROLENAME_FIELD_NUMBER;
    hash = (53 * hash) + getRoleName().hashCode();
    hash = (37 * hash) + ROLELEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getRoleLevel();
    hash = (37 * hash) + ISREADY_FIELD_NUMBER;
    hash = (53 * hash) + getIsReady();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xxicon.poker.message.RoomRoleInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxicon.poker.message.RoomRoleInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxicon.poker.message.RoomRoleInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxicon.poker.message.RoomRoleInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxicon.poker.message.RoomRoleInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xxicon.poker.message.RoomRoleInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xxicon.poker.message.RoomRoleInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xxicon.poker.message.RoomRoleInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xxicon.poker.message.RoomRoleInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xxicon.poker.message.RoomRoleInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xxicon.poker.message.RoomRoleInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xxicon.poker.message.RoomRoleInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xxicon.poker.message.RoomRoleInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code messages.RoomRoleInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:messages.RoomRoleInfo)
      com.xxicon.poker.message.RoomRoleInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xxicon.poker.message.Room.internal_static_messages_RoomRoleInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xxicon.poker.message.Room.internal_static_messages_RoomRoleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xxicon.poker.message.RoomRoleInfo.class, com.xxicon.poker.message.RoomRoleInfo.Builder.class);
    }

    // Construct using com.xxicon.poker.message.RoomRoleInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      index_ = 0;

      roleId_ = 0;

      roleName_ = "";

      roleLevel_ = 0;

      isReady_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xxicon.poker.message.Room.internal_static_messages_RoomRoleInfo_descriptor;
    }

    @java.lang.Override
    public com.xxicon.poker.message.RoomRoleInfo getDefaultInstanceForType() {
      return com.xxicon.poker.message.RoomRoleInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.xxicon.poker.message.RoomRoleInfo build() {
      com.xxicon.poker.message.RoomRoleInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xxicon.poker.message.RoomRoleInfo buildPartial() {
      com.xxicon.poker.message.RoomRoleInfo result = new com.xxicon.poker.message.RoomRoleInfo(this);
      result.index_ = index_;
      result.roleId_ = roleId_;
      result.roleName_ = roleName_;
      result.roleLevel_ = roleLevel_;
      result.isReady_ = isReady_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xxicon.poker.message.RoomRoleInfo) {
        return mergeFrom((com.xxicon.poker.message.RoomRoleInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xxicon.poker.message.RoomRoleInfo other) {
      if (other == com.xxicon.poker.message.RoomRoleInfo.getDefaultInstance()) return this;
      if (other.getIndex() != 0) {
        setIndex(other.getIndex());
      }
      if (other.getRoleId() != 0) {
        setRoleId(other.getRoleId());
      }
      if (!other.getRoleName().isEmpty()) {
        roleName_ = other.roleName_;
        onChanged();
      }
      if (other.getRoleLevel() != 0) {
        setRoleLevel(other.getRoleLevel());
      }
      if (other.getIsReady() != 0) {
        setIsReady(other.getIsReady());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xxicon.poker.message.RoomRoleInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xxicon.poker.message.RoomRoleInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int index_ ;
    /**
     * <pre>
     * 房间位置
     * </pre>
     *
     * <code>int32 index = 1;</code>
     * @return The index.
     */
    public int getIndex() {
      return index_;
    }
    /**
     * <pre>
     * 房间位置
     * </pre>
     *
     * <code>int32 index = 1;</code>
     * @param value The index to set.
     * @return This builder for chaining.
     */
    public Builder setIndex(int value) {
      
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 房间位置
     * </pre>
     *
     * <code>int32 index = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndex() {
      
      index_ = 0;
      onChanged();
      return this;
    }

    private int roleId_ ;
    /**
     * <code>int32 roleId = 2;</code>
     * @return The roleId.
     */
    public int getRoleId() {
      return roleId_;
    }
    /**
     * <code>int32 roleId = 2;</code>
     * @param value The roleId to set.
     * @return This builder for chaining.
     */
    public Builder setRoleId(int value) {
      
      roleId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 roleId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoleId() {
      
      roleId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object roleName_ = "";
    /**
     * <code>string roleName = 3;</code>
     * @return The roleName.
     */
    public java.lang.String getRoleName() {
      java.lang.Object ref = roleName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roleName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string roleName = 3;</code>
     * @return The bytes for roleName.
     */
    public com.google.protobuf.ByteString
        getRoleNameBytes() {
      java.lang.Object ref = roleName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string roleName = 3;</code>
     * @param value The roleName to set.
     * @return This builder for chaining.
     */
    public Builder setRoleName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roleName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string roleName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoleName() {
      
      roleName_ = getDefaultInstance().getRoleName();
      onChanged();
      return this;
    }
    /**
     * <code>string roleName = 3;</code>
     * @param value The bytes for roleName to set.
     * @return This builder for chaining.
     */
    public Builder setRoleNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roleName_ = value;
      onChanged();
      return this;
    }

    private int roleLevel_ ;
    /**
     * <code>int32 roleLevel = 4;</code>
     * @return The roleLevel.
     */
    public int getRoleLevel() {
      return roleLevel_;
    }
    /**
     * <code>int32 roleLevel = 4;</code>
     * @param value The roleLevel to set.
     * @return This builder for chaining.
     */
    public Builder setRoleLevel(int value) {
      
      roleLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 roleLevel = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoleLevel() {
      
      roleLevel_ = 0;
      onChanged();
      return this;
    }

    private int isReady_ ;
    /**
     * <code>int32 isReady = 5;</code>
     * @return The isReady.
     */
    public int getIsReady() {
      return isReady_;
    }
    /**
     * <code>int32 isReady = 5;</code>
     * @param value The isReady to set.
     * @return This builder for chaining.
     */
    public Builder setIsReady(int value) {
      
      isReady_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 isReady = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsReady() {
      
      isReady_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:messages.RoomRoleInfo)
  }

  // @@protoc_insertion_point(class_scope:messages.RoomRoleInfo)
  private static final com.xxicon.poker.message.RoomRoleInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xxicon.poker.message.RoomRoleInfo();
  }

  public static com.xxicon.poker.message.RoomRoleInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RoomRoleInfo>
      PARSER = new com.google.protobuf.AbstractParser<RoomRoleInfo>() {
    @java.lang.Override
    public RoomRoleInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RoomRoleInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RoomRoleInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RoomRoleInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xxicon.poker.message.RoomRoleInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

